### ISSUE TITLE
[Monthly Meeting] January 5, 2021 Andy Levy

### ISSUE THREAD

**Issue by bertwagner** [OhioNorthDatabaseTraining/Monthly-Meetings#2]
**GoToMeeting link**: https://global.gotomeeting.com/join/358150789

**Agenda Items**:
 - Officer nominations/voting
 - Explain ONDT and the end of PASS ONSSUG

**Todos for this meeting**:
 - [x] Update ondt.org with meeting details
 - [x] Email speaker reminding them of their commitment
 - [x] Email user group invite
