### ISSUE TITLE
[Monthly Meeting] Feburary 2, 2021 Michael J. Swart

### ISSUE THREAD

**Issue by bertwagner** [OhioNorthDatabaseTraining/Monthly-Meetings#3]
**GoToMeeting link**: https://global.gotomeeting.com/join/961360357

**Agenda Items**:
 - [ ] Review outstanding GitHub issues?

**Todos for this meeting**:
 - [x] Update ondt.org with meeting details
 - [ ] Email speaker reminding them of their commitment
 - [x] Email user group invite
