### ISSUE TITLE
[Monthly Meeting] March 2, 2021 Peter Shore

### ISSUE THREAD

**Issue by bertwagner** [OhioNorthDatabaseTraining/Monthly-Meetings#4]
**GoToMeeting link**: 

**Agenda Items**:
 - Item 1
 - Item 2
 - Item 3

**Todos for this meeting**:
 - [x] Update ondt.org with meeting details
 - [ ] Email speaker reminding them of their commitment
 - [ ] Email user group invite
