### ISSUE TITLE
[Monthly Meeting] April 6, 2021 Eugene Meidinger

### ISSUE THREAD

**Issue by bertwagner** [OhioNorthDatabaseTraining/Monthly-Meetings#5]
**GoToMeeting link**: 

**Agenda Items**:
 - Item 1
 - Item 2
 - Item 3

**Todos for this meeting**:
 - [ ] Update ondt.org with meeting details
 - [ ] Email speaker reminding them of their commitment
 - [ ] Email user group invite
